---
title: "git_00"
author: "Daniel A Soria Zuniga"
date: "june, 1, 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with a sequence of commits to the master branch.
Our project will be done using several commits to the master branch.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->"The sun was shining on the sea,  
      Shining with all his might:  
He did his very best to make  
      The billows smooth and bright —  
And this was odd, because it was  
      The middle of the night.  

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->
Mary sat musing on the lamp-flame at the table  
Waiting for Warren. When she heard his step,  
She ran on tip-toe down the darkened passage  
To meet him in the doorway with the news  
And put him on his guard. ‘Silas is back.’  
  
## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->
"The sun was shining on the sea,  
      Shining with all his might:  
He did his very best to make  
      The billows smooth and bright —  
And this was odd, because it was  
      The middle of the night.  
  
The moon was shining sulkily,  
      Because she thought the sun  
Had got no business to be there  
      After the day was done —  
"It's very rude of him," she said,  
      "To come and spoil the fun."  
  
## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
In ascetic silence, in stony skirts,  
God's handmaid falls on her face --  
Flash of an empty night, a forlorn desert waste,  
Shards of sunset upon the rocks.  
  
This land. Trodden, just like this, by a wandering sadness,  
Trailing in her thunders, calling her: 'Where art thou?'  
Speak to her, tell her of things that are other,  
Tell her of fields that are learning to smile.  
  
For it was your arms that held up her slumped head,  
For it was you who injected her bloodstream with youth,  
As she drank in the dew with noisy lips  
And bore a tractor in her heart.  

